### ISSUE TITLE
Don't copy extension assets to project root

### ISSUE THREAD

**Issue by mvuorre** [mvuorre/quarto-preprint#14]
When you render to quarto-preprint, the .svg files get copied to the project root. That sucks and shouldn't happen.

**Comment by danieltomasz** [comment]
Hi @mvuorre what you think about directly defining svg in the  template files? Laprepint is defining orcid in a file https://github.com/LaPreprint/typst/blob/c908cd05da8e13eb8add652a613d00add73d1f58/lapreprint.typ#L50

**Comment by mvuorre** [comment]
I think it would be sweet. I did not do this for two reasons:

1. Unsure if it works in .docx (that doesn't really matter tho)
2. Not sure if/how to implement the psyarxiv et cetera logos. Might just deprecate those in favor of simplifying this...

**Comment by danieltomasz** [comment]
If someone is using project yml someone can delete those files as postprocessing, it will not work for files not included to the project
````
project:
  title: "Quarto preprint"
  render: 
    - index.qmd
  output-dir: docs
  post-render: rm  orcid.svg psyarxiv.svg
 

execute:
  cache: true
 ```
