### ISSUE TITLE
Too much space before author and coma for authors ( at least 3 authors without orcid) 

### ISSUE THREAD

**Issue by danieltomasz** [mvuorre/quarto-preprint#27]
When the coma appears (at least 3 authors) and the authors doesnt have orcid and they aren't corresponding, additional space appears after affiliation superscript and before coma, example below:
```
---
title: Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...
running-head: Running head
author:
  - name: My Name
    email: myemail@example.com
    orcid: 0000-0000-0000-0000
    url: https://
    corresponding: true
    affiliation:
    - ref: 1
  - name: My Name
    url: https://
    affiliation:
      - ref: 1
  - name: My Name
    url: https://
    affiliation:
      - ref: 1
  - name: My Name
    url: https://
    affiliation:
      - ref: 1
affiliations:
  - id: 1
    name: Example University
    department: Example Department
abstract: |
  Abstract.
keywords: [list, keywords, here]
authornote: This is an example author note.
bibliography: bibliography.bib
format: preprint-typst
---
```
