### ISSUE TITLE
Left-align figure captions

### ISSUE THREAD

**Issue by mvuorre** [mvuorre/quarto-preprint#9]

**Comment by danieltomasz** [comment]
My workaround is to redefine it in yaml (with the addition of a space around a figure):

```yaml
format:
  preprint-typst:
    include-in-header:
      text: |
        #show figure: set block(inset: (top: 1em, bottom: 1em))
        #show figure: it => {
          align(center, it.body)
          align(left, it.caption)
        }
```
